#!/bin/bash

if [ "x$ENV" == "xprod" ]; then
    /usr/sbin/nginx &
    cd /usr/share/nginx/html
    gunicorn app:app \
        --bind localhost:8000 \
        --access-logfile - \
        --error-logfile - \
        --user www-data
else
    cd /usr/share/nginx/html
    python app.py
fi
